#!/bin/bash
#
# Author: Luis Daniel Lucio Quiroz <dlucio@okay.com.mx>
#

while getopts ":H:p:w:c:" opt; do
	case $opt in
		H)
			ethereum_node_ip=$OPTARG
			;;
		p)
			ethereum_node_port=$OPTARG
			;;
		w)
			ethereum_warning=$OPTARG
			;;
		c)
			ethereum_critical=$OPTARG
			;;
		\?)      
			echo "UNKNOWN- Invalid option: -$OPTARG" >&2
      			exit 3
      			;;
    		:)
	      		echo "UNKNOWN- Option -$OPTARG requires an argument." >&2
	      		exit 3
      		;;
	esac
done

if [ -z "$ethereum_node_ip" ]; then
	ethereum_node_ip=localhost
fi

if [ -z "$ethereum_node_port" ]; then
	ethereum_node_port=8545
fi

if [ -z "$ethereum_warning" ]; then
	ethereum_warning=10
fi

if [ -z "$ethereum_critical" ]; then
	ethereum_critical=5
fi

if [ "$ethereum_critical" -gt "$ethereum_warning" ]; then
	echo "UNKNOWN- Warning can not be less than Critical"
	exit 3
fi

#
# Get Local Data
#
local_json=$(curl http://$ethereum_node_ip:$ethereum_node_port -sSf -X POST --data '{"jsonrpc":"2.0","method":"eth_mining","params":[],"id":71}' -H "Content-Type: application/json")
if [ $? -ne "0" ]; then
	echo "UNKNOWN- Could not fetch local mining state"
	exit 3
fi

declare -A localarray
while IFS="=" read -r key value
do
    local_array[$key]="$value"
done < <(echo $local_json |jq -r "to_entries|map(\"\(.key)=\(.value)\")|.[]" -)

is_mining=${local_array[result]}

if [ $is_mining == "false" ]; then
	echo "CRITICAL- No mining"
	exit 2
fi

local_json2=$(curl http://$ethereum_node_ip:$ethereum_node_port -sSf -X POST --data '{"jsonrpc":"2.0","method":"eth_hashrate","params":[],"id":71}' -H "Content-Type: application/json")
if [ $? -ne "0" ]; then
	echo "UNKNOWN- Could not fetch local mining state"
	exit 3
fi

declare -A local_array2
while IFS="=" read -r key value
do
    local_array2[$key]="$value"
done < <(echo $local_json2 |jq -r "to_entries|map(\"\(.key)=\(.value)\")|.[]" -)

hash_rate16=${local_array2[result]}
hash_rate10=$((hash_rate16))

output="mining = $is_mining, hash rate = $hash_rate10"

if [ "$hash_rate10" -ge "$ethereum_warning" ]; then
	echo "OK- $output"
	exit 0
elif [ "$hash_rate10" -le "$ethereum_warning" ] && [ "$hash_rate10" -gt "$ethereum_critical" ]; then
	echo "WARNING- $output"
	exit 1
elif [ "$hash_rate10" -le "$ethereum_critical" ]; then
	echo "CRITICAL- $output"
	exit 2
else
	echo "UNKNOWN- $output"
	exit 3
fi
